- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Include OS-specific setup.
  include: "setup_{{ ansible_os_family }}.yml"

- name: Create cache root directory.
  file:
    path: "{{ conga_config.dispatcher.cache.rootPath }}"
    state: directory
    owner: "{{ apache_user }}"
    group: "{{ apache_group }}"

- name: Setup SSL if required by CONGA variant.
  include: setup_ssl.yml
  when: "'ssl' in conga_variants"

# copy all config files but leave out distribution specific files
- name: Copy all CONGA files except vhosts and conf
  include_role:
    name: conga-files
  vars:
    base_path: "{{ apache_config_path }}"
    handlers: [ restart apache ]
    files: "{{ conga_files_paths | select('match', '^(?!(vhosts|conf).d/)') | list }}"
    directories: "{{ conga_directories | select('match', '^(?!(vhosts|conf).d)') | list }}"

- name: Enable CONGA sites.
  include: "enable_sites_{{ ansible_os_family }}.yml"
