# Shims for Debian compatibility
- name: Create /etc/ssl/private link for SSL key files.
  file:
    src: /etc/pki/tls/private
    dest: /etc/ssl/private
    state: link
  when: "'ssl' in conga_variants"

- name: Set APACHE_LOG_DIR variable.
  lineinfile:
    dest: "{{ apache_config_path }}/conf.d/00-envvars.conf"
    line: 'Define APACHE_LOG_DIR /var/log/httpd'
    create: yes
  notify:
    - restart apache
